apiVersion: v1
data:
  data: name:installer-platform, ns:null, status:{"componentStatus":{"cko-diagnostic":{"lastUpdated":"101010-210-100
    210:02:02","mode":"managed","type":"connectivity-checker"},"cko-gitops":{"lastUpdated":"101010-210-100
    210:02:02","mode":"managed","type":"argo"}},"observedGeneration":1,"operatorStatus":"Running"},
    status_b64:eyJjb21wb25lbnRTdGF0dXMiOnsiY2tvLWRpYWdub3N0aWMiOnsibGFzdFVwZGF0ZWQiOiIxMDEwMTAtMjEwLTEwMCAyMTA6MDI6MDIiLCJtb2RlIjoibWFuYWdlZCIsInR5cGUiOiJjb25uZWN0aXZpdHktY2hlY2tlciJ9LCJja28tZ2l0b3BzIjp7Imxhc3RVcGRhdGVkIjoiMTAxMDEwLTIxMC0xMDAgMjEwOjAyOjAyIiwibW9kZSI6Im1hbmFnZWQiLCJ0eXBlIjoiYXJnbyJ9fSwib2JzZXJ2ZWRHZW5lcmF0aW9uIjoxLCJvcGVyYXRvclN0YXR1cyI6IlJ1bm5pbmcifQ==
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    netop-manager-resource: installer.controller.netop-manager.io
    notification.notification-ctrlr.netop-manager.io: exclude
  name: bm2acicni-installer.controller.netop-manager.io
  namespace: netop-manager-system
